runtime: custom
env: flex

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.5
resources:
  cpu: 2
  memory_gb: 4
  disk_size_gb: 10
network:
  name: projects/edts-playpen-leonardi/global/networks/edts-gis-vpc-dev
  subnetwork_name: asia-southeast2
  instance_ip_mode: internal
vpc_access_connector:
  name: projects/edts-playpen-leonardi/locations/asia-southeast2/connectors/edts-gis-dev-connector
  egress_setting: all-traffic