steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--build-arg=VITE_CORE_HOSTNAME=${_CORE_HOSTNAME}'
      - '--tag=${_AR_IMAGE}'
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '${_AR_IMAGE}'
  - name: gcr.io/cloud-builders/gcloud
    args:
      - app
      - deploy
      - app.yaml
      - '--image-url=${_AR_IMAGE}'
images:
  - '${_AR_IMAGE}'
options:
  dynamicSubstitutions: true
substitutions:
  _ENVIRONMENT: '' # Overwrite in Cloud Build
  _CORE_HOSTNAME: '' # Overwrie in Cloud Build
  _PROJECT_ID: edts-playpen-leonardi
  _PROJECT_CODE: '617510130799'
  _REGION: asia-southeast2
  _IMAGE: edts-gis-web-report
  _REPOSITORY: edts-gis-images
  _AR_IMAGE: ${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/${_IMAGE}:${_ENVIRONMENT}-internal
